#!/usr/bin/env /usr/bin/bash

source "./settings.env"

if [ ! -z "${I_EDITED_THIS_FILE}" ] && [ ${I_EDITED_THIS_FILE} -eq 0 ]
then	echo "You really want to review settings.env and edit this file before running this script."
	exit 2
fi

print_danted_base_config() {
	PROXY_PORT=$1; shift
	cat <<EOF
#
# this file was auto-generated by $0.  any changes made to this file will be over-written
# next time you use $0, so if you want these changes preserved, copy the file to a different
# filename and update settings.env with this filename within PROXY_CONFIG
#
errorlog: stderr
logoutput: stdout
# debug: 2

internal: eth0 port = ${PROXY_PORT}
external: tun0

user.notprivileged: dante

clientmethod: none
socksmethod: none

EOF
}

print_danted_access_config() {
	SUBNET=$1; shift
	cat <<EOF | sed "s!%%AUTHORIZED_SUBNET%%!${SUBNET}!g"
#
# access rules for subnet %%AUTHORIZED_SUBNET%%

client pass {
	from: %%AUTHORIZED_SUBNET%% to: 0.0.0.0/0
	log: error # connect disconnect
}

socks pass {
	from: %%AUTHORIZED_SUBNET%% to: 0.0.0.0/0
	command: bind connect udpassociate
	log: error # connect disconnect iooperation
}

socks pass {
	from: 0.0.0.0/0 to: %%AUTHORIZED_SUBNET%%
	command: bindreply udpreply
	log: error # connect disconnect iooperation
}

EOF
}

if [ ! -z "${PROXY_CONFIG}" ] 
then	if [ -e "${PROXY_CONFIG}" ]
	then	_PROXY_CONFIG=${PROXY_CONFIG}
	else	echo "ERROR: PROXY_CONFIG ${PROXY_CONFIG} specified, but not found."
		echo "	To automatically generate a configuration file, comment out"
		echo "	PROXY_CONFIG parameter in ./settings.env."
		exit 2
	fi
else	echo "Generating proxy configuration file."
	_PROXY_CONFIG="danted.conf.autogen"
	(
		print_danted_base_config $PROXY_PORT
		for subnet in ${LOCAL_SUBNETS}
		do	echo
			print_danted_access_config ${subnet}
		done
	) > "./config/${_PROXY_CONFIG}"
fi

export _PROXY_CONFIG

docker-compose --env-file=settings.env build -q && \
	docker-compose --env-file=settings.env up -d

if [ $? -eq 0 ] 
then	cat<<-EOF

	Reminder!!!

	You can modify the files within the config/ subfolder and restart the containers without re-running this script.
	Only re-run this script if you modify parameters within settings.env.

EOF
fi

